server:
  port: 1919

logging:
  level:
    com.alibaba: DEBUG
    com.alibaba.nacos.client.naming: INFO
    org.springframework.http.server.reactive: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG