server:
  port: 1919

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: user
          uri: lb://overtime-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: compensate
          uri: lb://overtime-compensate
          predicates:
            - Path=/compensate/**
          filters:
            - StripPrefix=1

        - id: dictionary
          uri: lb://overtime-dictionary
          predicates:
            - Path=/dictionary/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG